//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodAPIv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string PrepareTime { get; set; }
        public string Nationality { get; set; }
        public string Ingredients { get; set; }
        public string Steps { get; set; }
        public string Privacy { get; set; }
        public Nullable<int> LoveCount { get; set; }
        public Nullable<int> ShareCount { get; set; }
        public Nullable<int> ReviewsCount { get; set; }
        public Nullable<double> ReviewsRateTotal { get; set; }
        public Nullable<long> CreatedDate { get; set; }
        public int UserId { get; set; }
        public List<string> Categories { get; set; }
        public List<string> ImagesUrls { get; set; }
    }
}
