//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodAPIv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public string ReviewText { get; set; }
        public string ReviewResult { get; set; }
        public Nullable<bool> IsCreator { get; set; }
        public Nullable<long> CreatedData { get; set; }
        public int UserId { get; set; }
        public int RecipeId { get; set; }
    }
}
