//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodAPIv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public string ImageUrl { get; set; }
        public string Phone { get; set; }
        public string Bio { get; set; }
        public string Nationality { get; set; }
        public Nullable<long> CreatedDate { get; set; }
        public Nullable<int> FollowersCount { get; set; }
        public List<string> Links { get; set; }
    }
}
