// <auto-generated />
namespace FoodAPIv1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Model02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model02));
        
        string IMigrationMetadata.Id
        {
            get { return "202104090533272_Model02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
